// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-axios'

import type { UserLoginData, UserLoginError, UserLoginResponse } from './types.gen'

export const client = createClient(createConfig())

export class AuthService {

	/**
	 * Logs user into the system
	 */
	public static userLogin<ThrowOnError extends boolean = false>(options: Options<UserLoginData, ThrowOnError>) {
		return (options?.client ?? client).post<UserLoginResponse, UserLoginError, ThrowOnError>({
			...options,
			url: '/auth/login'
		})
	}

}