// This file is auto-generated by @hey-api/openapi-ts

export type UserLoginData = {
	body: {
		email: string;
		password: string;
	};
};

export type UserLoginResponse = ({
	refresh_token: string;
	access_token: string;
});

export type UserLoginError = (unknown);