// This file is auto-generated by @hey-api/openapi-ts

/**
 * Модель пользователя системы
 */
export type User = {

	/**
	 * Уникальный идентификатор пользователя
	 */
	id: string;

	/**
	 * Email адрес пользователя
	 */
	email: string;

	/**
	 * Полное имя пользователя
	 */
	full_name: string;
	role: UserRole;
};

export type UserRole = 'CONTRACTOR' | 'CUSTOMER' | 'INSPECTOR';

export const UserRole = {
	CONTRACTOR: 'CONTRACTOR',
	CUSTOMER: 'CUSTOMER',
	INSPECTOR: 'INSPECTOR'
} as const

export type UserLoginData = {
	body: {
		email: string;
		password: string;
	};
};

export type UserLoginResponse = ({
	refresh_token: string;
	access_token: string;
});

export type UserLoginError = (unknown);

export type UserLogoutResponse = (void);

export type UserLogoutError = (unknown);

export type RefreshTokenData = {
	body: {
		refresh_token: string;
	};
};

export type RefreshTokenResponse = ({
	access_token: string;
});

export type RefreshTokenError = unknown;

export type GetAuthenticatedUserResponse = (User);

export type GetAuthenticatedUserError = (unknown);